apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/instance: pod-scheduler-replica-modifier-rolebinding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pod-scheduler
    app.kubernetes.io/part-of: pod-scheduler
    app.kubernetes.io/managed-by: kustomize
  name: pod-scheduler-replica-modifier-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-scheduler-replica-modifier-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: pod-scheduler