apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-manager
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - pod.loop.dev
  resources:
  - clusterschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pod.loop.dev
  resources:
  - clusterschedules/finalizers
  verbs:
  - update
- apiGroups:
  - pod.loop.dev
  resources:
  - clusterschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - pod.loop.dev
  resources:
  - schedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pod.loop.dev
  resources:
  - schedules/finalizers
  verbs:
  - update
- apiGroups:
  - pod.loop.dev
  resources:
  - schedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
    - "apps"
  resources:
    - "deployments"
    - "statefulsets"
  verbs:
    - "get"
    - "list"
    - "watch"
    - "update"
    - "patch"
- apiGroups:
    - "apps"
  resources:
    - "deployments/scale"
    - "statefulsets/scale"
  verbs:
    - "patch"
- apiGroups:
    - ""
  resources:
    - "pods"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups:
    - "autoscaling"
  resources:
    - "horizontalpodautoscalers"
  verbs:
    - "get"
    - "list"
    - "watch"
    - "update"
    - "patch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator.fullname" . }}-jobs
  labels:
    {{- include "operator.labels" . | nindent 4 }}
rules:
- apiGroups:
    - "apps"
  resources:
    - "deployments"
    - "statefulsets"
  verbs:
    - "get"
    - "list"
    - "watch"
    - "update"
    - "patch"
- apiGroups:
    - "apps"
  resources:
    - "deployments/scale"
    - "statefulsets/scale"
  verbs:
    - "patch"
- apiGroups:
    - ""
  resources:
    - "pods"
  verbs:
    - "get"
    - "list"
    - "watch"
- apiGroups:
    - "autoscaling"
  resources:
    - "horizontalpodautoscalers"
  verbs:
    - "get"
    - "list"
    - "watch"
    - "update"
    - "patch"