{{- if or .Values.serviceAccount.create .Values.serviceAccount.name -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "operator.fullname" . }}-manager
  labels:
    {{- include "operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator.fullname" . }}-manager
subjects:
- kind: ServiceAccount
  name: {{ include "operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}